BestRestaurant/Models/BestRestaurantContext.cs
using Microsoft.EntityFrameworkCore;

namespace BestRestaurant.Models
{
  public class BestRestaurantContext : DbContext
  {
    public virtual DbSet<Restaurant> Restaurants { get; set; }
    public DbSet<Dish> Dishes { get; set; }

    public BestRestaurantContext(DbContextOptions options) : base(options) { }

    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
    {
      optionsBuilder.UseLazyLoadingProxies();
    }
  }
}

BestRestaurant/Models/Dish.cs
namespace BestRestaurant.Models
{
  public class Dish
  {
    public int DishId { get; set; }
    public string Name { get; set; }
    public int Rating { get; set; }
    public string Description { get; set; }
    public int RestaurantId { get; set; }
    public virtual Restaurant Restaurant { get; set; }
  }
}

BestRestaurant/Models/Restaurant.cs
using System.Collections.Generic;

namespace BestRestaurant.Models
{
  public class Restaurant
  {
    public Restaurant()
    {
      Dishes = new HashSet<Dish>();
    }
    public virtual ICollection<Dish> Dishes { get; set; }

    public int RestaurantId { get; set; }

    public string Name { get; set; }

    public int RoomRating { get; set; }


  }
}

BestRestaurant/Controllers/DishesController.cs
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Mvc;
using BestRestaurant.Models;
using System.Collections.Generic;
using System.Linq;

namespace BestRestaurant.Controllers
{
  public class DishesController : Controller
  {
    private readonly BestRestaurantContext _db;

    public DishesController(BestRestaurantContext db)
    {
      _db = db;
    }

    public ActionResult Index()
    {
      List<Dish> model = _db.Dishes.Include(dish => dish.Restaurant).ToList();
      return View(model);
    }

    public ActionResult Create()
    {
      ViewBag.RestaurantId = new SelectList(_db.Restaurants, "RestaurantId", "Name");
      return View();
    }

    [HttpPost]
    public ActionResult Create(Dish dish)
    {
      _db.Dishes.Add(dish);
      _db.SaveChanges();
      return RedirectToAction("Index");
    }

    public ActionResult Details(int id)
    {
      Dish thisDish = _db.Dishes.FirstOrDefault(dish => dish.DishId == id);
      return View(thisDish);
    }

    public ActionResult Edit(int id)
    {
      var thisDish = _db.Dishes.FirstOrDefault(dish => dish.DishId == id);
      ViewBag.RestaurantId = new SelectList(_db.Restaurants, "RestaurantId", "Name");
      return View(thisDish);
    }

    [HttpPost]
    public ActionResult Edit(Dish dish)
    {
      _db.Entry(dish).State = EntityState.Modified;
      _db.SaveChanges();
      return RedirectToAction("Index");
    }

    public ActionResult Delete(int id)
    {
      var thisDish = _db.Dishes.FirstOrDefault(dish => dish.DishId == id);
      return View(thisDish);
    }

    [HttpPost, ActionName("Delete")]
    public ActionResult DeleteConfirmed(int id)
    {
      var thisDish = _db.Dishes.FirstOrDefault(dish => dish.DishId == id);
      _db.Dishes.Remove(thisDish);
      _db.SaveChanges();
      return RedirectToAction("Index");
    }
  }
}

BestRestaurant/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;

namespace BestRestaurant.Controllers
{
  public class HomeController : Controller
  {

    [HttpGet("/")]
    public ActionResult Index()
    {
      return View();
    }

  }
}

BestRestaurant/Controllers/RestaurantsController.cs
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Mvc;
using BestRestaurant.Models;
using System.Collections.Generic;
using System.Linq;

namespace BestRestaurant.Controllers
{
  public class RestaurantsController : Controller
  {
    private readonly BestRestaurantContext _db;

    public RestaurantsController(BestRestaurantContext db)
    {
      _db = db;
    }
    public ActionResult Index()
    {
      List<Restaurant> model = _db.Restaurants.ToList();
      return View(model);
    }

    public ActionResult Create()
    {
      return View();
    }

    [HttpPost]
    public ActionResult Create(Restaurant restaurant)
    {
      _db.Restaurants.Add(restaurant);
      _db.SaveChanges();
      return RedirectToAction("Index");
    }

    public ActionResult Details(int id)
    {
      Restaurant thisRestaurant = _db.Restaurants.FirstOrDefault(r => r.RestaurantId == id);
      return View(thisRestaurant);
    }
    public ActionResult Edit(int id)
    {
      Restaurant thisRestaurant = _db.Restaurants.FirstOrDefault(r => r.RestaurantId == id);
      return View(thisRestaurant);
    }

    [HttpPost]
    public ActionResult Edit(Restaurant restaurant)
    {
      _db.Entry(restaurant).State = EntityState.Modified;
      _db.SaveChanges();
      return RedirectToAction("Index");
    }

    public ActionResult Delete(int id)
    {
      Restaurant thisRestaurant = _db.Restaurants.FirstOrDefault(r => r.RestaurantId == id);
      return View(thisRestaurant);
    }

    [HttpPost, ActionName("Delete")]
    public ActionResult DeleteConfirmed(int id)
    {
      Restaurant thisRestaurant = _db.Restaurants.FirstOrDefault(restaurant => restaurant.RestaurantId == id);
      _db.Restaurants.Remove(thisRestaurant);
      _db.SaveChanges();
      return RedirectToAction("Index");
    }
  }
}

BestRestaurant/Views/Dishes/Create.cshtml
@{ Layout = "_Layout"; }

@model BestRestaurant.Models.Dish

<h4>Add a new dish</h4>
@using (Html.BeginForm())
{
  @Html.LabelFor(model => model.Name)
  @Html.TextBoxFor(model => model.Name)
  @Html.LabelFor(model => model.Description)
  @Html.TextBoxFor(model => model.Description)
  @Html.LabelFor(model => model.Restaurant)
  @Html.DropDownList("RestaurantId")
  <label for="RoomRating">Rating</label>
  <input id="RoomRating" name="Rating" type="number" min=0 max=5 />
  <button type="submit">Add</button>
}
<p>@Html.ActionLink("Show all dishes", "Index")</p>

BestRestaurant/Views/Dishes/Details.cshtml
@{
  Layout = "_Layout";
}

@model BestRestaurant.Models.Dish

<h2>Dish Details</h2>
<hr />
<h3>@Html.DisplayNameFor(model => model.Description): @Html.DisplayFor(model => model.Description)</h3>
<p>@Html.ActionLink("Edit Dish", "Edit", new { id = Model.DishId })</p>
<p>@Html.ActionLink("Delete Dish", "Delete", new { id = Model.DishId })</p>
<p>@Html.ActionLink("Back to list", "Index")</p>

BestRestaurant/Views/Dishes/Edit.cshtml
@{ Layout = "_Layout"; }

@model BestRestaurant.Models.Dish

<h2>Edit</h2>

<h4>Edit this dish: @Html.DisplayFor(model => model.Name)</h4>
@using (Html.BeginForm())
{
  @Html.HiddenFor(model => model.DishId)

  @Html.LabelFor(model => model.Name)
  @Html.TextBoxFor(model => model.Name)
  @Html.LabelFor(model => model.Description)
  @Html.TextBoxFor(model => model.Description)
  @Html.LabelFor(model => model.Restaurant)
  @Html.DropDownList("RestaurantId")
  <label for="RoomRating">Rating</label>
  <input id="RoomRating" name="Rating" type="number" min=0 max=5 value="@Model.Rating" />
  <button type="submit">Save</button>
}
<p>@Html.ActionLink("Show all items", "Index")</p>

BestRestaurant/Views/Dishes/Index.cshtml
<!-- prettier-ignore -->
@{ Layout = "_Layout"; } 
@model List<Dish>;
@using Microsoft.EntityFrameworkCore; 
@using BestRestaurant.Models; 
<!-- prettier-ignore-end -->

<h1>Dishes</h1>

@if (@Model.Count == 0) {
<h3>No dishes have been added yet!</h3>
} @foreach (Dish dish in Model) {
<li>
  @Html.ActionLink($"{dish.Name}", "Details", new { id = dish.DishId }) |
  @dish.Restaurant.Name
</li>
}

<p>@Html.ActionLink("Add new dish", "Create")</p>
<p>@Html.ActionLink("Home", "Index", "Home")</p>

BestRestaurant/Views/Home/Index.cshtml
@{ Layout = "_Layout"; }

<h1>Welcome to the Best Restaurants list!</h1>
<p>@Html.ActionLink("See all dishes", "Index", "Dishes")</p> <p>@Html.ActionLink("See all restaurants", "Index", "Restaurants")</p>

BestRestaurant/Views/Restaurants/Create.cshtml
@{ Layout = "_Layout"; }

@model BestRestaurant.Models.Restaurant

<h4>Add a New Restaurant</h4>
@using (Html.BeginForm())
{
  @Html.LabelFor(model => model.Name)
  @Html.TextBoxFor(model => model.Name)
  <label for="RoomRating">Room Rating</label>
  <input id="RoomRating" name="RoomRating" type="number" min=0 max=5 />
  <button type="submit">Add</button>
}
<p>@Html.ActionLink("Cancel", "Index")</p>

BestRestaurant/Views/Restaurants/Delete.cshtml
@{ Layout = "_Layout"; }

@model BestRestaurant.Models.Restaurant

<h2>Are you sure you want to delete this?</h2>

@Html.DisplayNameFor(model => model.Name): @Html.DisplayFor(model => model.Name)
@Html.DisplayNameFor(model => model.RoomRating): @Html.DisplayFor(model => model.RoomRating)
@using (Html.BeginForm())
{
  <input type="submit" value="Delete" />
}
@Html.ActionLink("Back to List", "Index")

BestRestaurant/Views/Restaurants/Details.cshtml
@{ Layout = "_Layout"; }

@model BestRestaurant.Models.Restaurant

<h2>Restaurant Details</h2>
<hr/>
<h3>@Html.DisplayNameFor(model => model.Name): @Html.DisplayFor(model => model.Name)</h3>
<h3>@Html.DisplayNameFor(model => model.RoomRating): @Html.DisplayFor(model => model.RoomRating)</h3>
<p>@Html.ActionLink("Edit Restaurant", "Edit", new { id = Model.RestaurantId })</p>
<p>@Html.ActionLink("Delete Restaurant", "Delete", new { id = Model.RestaurantId })</p>
<p>@Html.ActionLink("Back to list", "Index")</p>

BestRestaurant/Views/Restaurants/Edit.cshtml
@{ Layout = "_Layout"; }

@model BestRestaurant.Models.Restaurant

<h2>Edit</h2>

<h4>Edit this restaurant: @Html.DisplayFor(model => model.Name)</h4>

@using (Html.BeginForm())
{
  @Html.HiddenFor(model => model.RestaurantId)

  @Html.LabelFor(model => model.Name)
  @Html.EditorFor(model => model.Name)
  <label for="RoomRating">Room Rating</label>
  <input id="RoomRating" name="RoomRating" type="number" min=0 max=5 />
  <button type="submit">Save</button>
}
<p>@Html.ActionLink("Back to list", "Index")</p>

BestRestaurant/Views/Restaurants/Index.cshtml
@{ Layout = "_Layout"; }

@using BestRestaurant.Models;

<h1>Restaurants</h1>

@if (@Model.Count == 0)
{
  <h3>No restaurants have been added yet!</h3>
} 

<ul>
  @foreach(Restaurant restaurant in Model)
  {
    <li>@Html.ActionLink($"{restaurant.Name}", "Details", new { id = restaurant.RestaurantId })</li>
  }
</ul>

<p>@Html.ActionLink("Add new restaurant", "Create")</p>
<p>@Html.ActionLink("Home", "Index", "Home")</p>

BestRestaurant/Views/Shared/Footer.cshtml
<footer>Bottom div content</footer>

BestRestaurant/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>Best Restaurants!</title>
    <!-- <link rel='stylesheet' href='https://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css'> -->
    <link rel="stylesheet" href="~/styles/reset.css">
    <link rel="stylesheet" href="~/styles/main.css">
  </head>
  <body>
    <main>
      @RenderBody()
    </main>
    @Html.Partial("Footer")
  </body>
</html>